apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: conta-api-dev-fernandoe-com
spec:
  secretName: conta-api-dev-fernandoe-com-tls
  issuerRef:
    name: ortopedica-letsencrypt
  commonName: conta-api.dev.fernandoe.com
  dnsNames:
    - conta-api.dev.fernandoe.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - conta-api.dev.fernandoe.com
