apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ortopedica-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:ortopedica
  rules:
    - host: conta-api.dev.fernandoe.com
      http:
        paths:
          - backend:
              serviceName: conta-api
              servicePort: 80
  tls:
    - hosts:
        - conta-api.dev.fernandoe.com
      secretName: conta-api-dev-fernandoe-com-tls
